name: read-yaml

on:
  workflow_call:
    inputs:
      file_name:
        required: true
        type: string
      templates_repo_ref:
        description: "Git ref of ml-mlops-templates to check out"
        required: true
        type: string
    outputs:
      location:
        description: "The resource group to use"
        value: ${{ jobs.read-yaml.outputs.location }}
      namespace:
        description: "Namespace of the resources"
        value: ${{ jobs.read-yaml.outputs.namespace }}
      postfix:
        description: "Postfix for the resource names"
        value: ${{ jobs.read-yaml.outputs.postfix }}
      environment:
        description: "Environment"
        value: ${{ jobs.read-yaml.outputs.environment }}
      enable_aml_computecluster:
        description: "Boolean to decide whether to deploy an AML compute cluster or not"
        value: ${{ jobs.read-yaml.outputs.enable_aml_computecluster }}
      enable_monitoring:
        description: "Boolean to decide whether to enable monitoring"
        value: ${{ jobs.read-yaml.outputs.enable_monitoring }}
      resource_group:
        description: "The resource group to use"
        value: ${{ jobs.read-yaml.outputs.resource_group }}
      aml_workspace:
        description: "The aml_workspace to use"
        value: ${{ jobs.read-yaml.outputs.aml_workspace }}
      storage_account:
        description: "The storage account"
        value: ${{ jobs.read-yaml.outputs.storage_account }}
      key_vault:
        description: "The key vault"
        value: ${{ jobs.read-yaml.outputs.key_vault }}
      app_insights:
        description: "The application insights"
        value: ${{ jobs.read-yaml.outputs.app_insights }}
      load_test_resource:
        description: "The load test resource"
        value: ${{ jobs.read-yaml.outputs.load_test_resource }}
      action_group_name:
        description: "The action group name for alerts"
        value: ${{ jobs.read-yaml.outputs.action_group_name }}
      bep:
        description: "The batch endpoint"
        value: ${{ jobs.read-yaml.outputs.bep }}
      oep:
        description: "The online endpoint"
        value: ${{ jobs.read-yaml.outputs.oep }}
      terraform_version:
        description: "Terraform version"
        value: ${{ jobs.read-yaml.outputs.terraform_version }}
      terraform_workingdir:
        description: "Terraform State working directory"
        value: ${{ jobs.read-yaml.outputs.terraform_workingdir }}
      terraform_st_location:
        description: "Terraform State location"
        value: ${{ jobs.read-yaml.outputs.terraform_st_location }}
      terraform_st_resource_group:
        description: "Terraform State Resource Group"
        value: ${{ jobs.read-yaml.outputs.terraform_st_resource_group }}
      terraform_st_storage_account:
        description: "Terraform State Storage Account"
        value: ${{ jobs.read-yaml.outputs.terraform_st_storage_account }}
      terraform_st_container_name:
        description: "Terraform State Container name"
        value: ${{ jobs.read-yaml.outputs.terraform_st_container_name }}
      terraform_st_key:
        description: "Terraform State Key"
        value: ${{ jobs.read-yaml.outputs.terraform_st_key }}
jobs:
  read-yaml:
    runs-on: ubuntu-latest
    outputs:
      location: ${{  steps.read_action_js.outputs.location }}
      namespace: ${{  steps.read_action_js.outputs.namespace }}
      postfix: ${{  steps.read_action_js.outputs.postfix }}
      environment: ${{  steps.read_action_js.outputs.environment }}
      enable_aml_computecluster: ${{  steps.read_action_js.outputs.enable_aml_computecluster }}
      enable_monitoring: ${{  steps.read_action_js.outputs.enable_monitoring }}
      resource_group: ${{  steps.read_action_js.outputs.resource_group }}
      aml_workspace: ${{  steps.read_action_js.outputs.aml_workspace }}
      storage_account: ${{  steps.read_action_js.outputs.storage_account }}
      key_vault: ${{  steps.read_action_js.outputs.key_vault }}
      app_insights: ${{  steps.read_action_js.outputs.app_insights }}
      load_test_resource: ${{  steps.read_action_js.outputs.load_test_resource }}
      action_group_name: ${{  steps.read_action_js.outputs.action_group_name }}
      bep: ${{  steps.read_action_js.outputs.bep }}
      oep: ${{  steps.read_action_js.outputs.oep }}
      terraform_version: ${{  steps.read_action_js.outputs.terraform_version }}
      terraform_workingdir: ${{  steps.read_action_js.outputs.terraform_workingdir }}
      terraform_st_location: ${{  steps.read_action_js.outputs.terraform_st_location }}
      terraform_st_resource_group: ${{  steps.read_action_js.outputs.terraform_st_resource_group }}
      terraform_st_storage_account: ${{  steps.read_action_js.outputs.terraform_st_storage_account }}
      terraform_st_container_name: ${{  steps.read_action_js.outputs.terraform_st_container_name }}
      terraform_st_key: ${{  steps.read_action_js.outputs.terraform_st_key }}
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4
      - name: Checkout templates repository
        uses: actions/checkout@v4
        with:
          repository: Eedi/ml-mlops-templates
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ inputs.templates_repo_ref }}
          path: templates_repo
      - name: Read test
        uses: ./templates_repo/read_yaml_action
        id: read_action_js
        with:
          config: ${{ github.workspace }}/${{ inputs.file_name }}
      - name: Echo outputs
        run: |
          echo "AML Workspace: ${{ steps.read_action_js.outputs.aml_workspace }}"
          echo "Storage Account: ${{ steps.read_action_js.outputs.storage_account }}"
          echo "BEP: ${{ steps.read_action_js.outputs.bep }}"
